### ISSUE TITLE
Improved lib usage for address

### ISSUE THREAD

**Issue by ericmuyser** [hyperbridge/funding-protocol#27]
We can wrap Project and ProjectStorage in a struct, and bind to those so we don't muddy up the global `address` interface. Here: https://github.com/hyperbridge/funding-protocol/blob/funding-upgradeability/smart-contracts/ethereum/contracts/Project.sol#L15

**Comment by 0xwalid** [comment]
https://gist.github.com/izqui/11a85aae6c749eba9841465c8a47ccc6#file-counter-sol-L2

**Comment by JordoBrooks** [comment]
Closed by #34
