### ISSUE TITLE
Not all contracts should accept ETH

### ISSUE THREAD

**Issue by ericmuyser** [hyperbridge/funding-protocol#5]
https://github.com/decent-bet/platform-frontend/blob/master/contracts/House/HouseLottery.sol#L115

Satisfaction for this issue would be to just double check and/or write a test that our contracts cant receive ETH or ERC20s unless intended

**Comment by ericmuyser** [comment]
Could you please write a test for this while doing the deposit/withdrawal stuff @0xwalid ?

**Comment by 0xwalid** [comment]
we can't control depositing of ERC20 tokens since they are external contracts but for eth, I added a fallback function to our vault that reverts eth deposits

**Comment by 0xwalid** [comment]
@JordoBrooks @ashtan19 can you please add the same fallback function in all your contracts?

**Comment by JordoBrooks** [comment]
Closed by #33
